/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    war
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    // servlet
    implementation("org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1")
    implementation("jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0")
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")

    implementation("com.google.guava:guava:31.1-jre")

    implementation("com.h2database:h2:1.3.167")

    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-dbcp2:2.9.0")

    // spring
    implementation("org.springframework:spring-jdbc:6.0.6")

    implementation("ch.qos.logback:logback-classic:1.4.5")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.1")

    // embeded tomcat
    implementation("org.apache.tomcat.embed:tomcat-embed-core:10.1.5")

    // test
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.assertj:assertj-core:3.24.2")
    testImplementation("org.springframework:spring-test:6.0.6")
}

group = "org.nhnnext"
version = "1.0"
description = "jwp-basic"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.war {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

tasks.processResources {
    duplicatesStrategy = org.gradle.api.file.DuplicatesStrategy.INCLUDE
}